##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = iwgtk-floating
    match:class = org.twosheds.iwgtk
    float = on
    move = (monitor_w-435) 40
    size = 400 600
}

windowrule {
    name = blueman-floating
    match:class = blueman-manager
    float = on
    move = (monitor_w-480) 40
    size = 400 600
}

xwayland {
  force_zero_scaling = true
}
