# gruvbox material dark (medium) — https://github.com/sainnhe/gruvbox-material
background       = 0xff282828
base             = 0xff32302f
alternate_base   = 0xff45403d
text             = 0xffd4be98
bright_text      = 0xffddc7a1
link_text        = 0xff7daea3   # blue
accent           = 0xffa9b665   # green
accent_secondary = 0xffd8a657   # yellow
