# nord — https://www.nordtheme.com
background       = 0xff2e3440   # nord0
base             = 0xff3b4252   # nord1
alternate_base   = 0xff434c5e   # nord2
text             = 0xffd8dee9   # nord4
bright_text      = 0xffeceff4   # nord6
link_text        = 0xff88c0d0   # nord8
accent           = 0xff88c0d0   # nord8
accent_secondary = 0xff81a1c1   # nord9
