# tokyonight night — https://github.com/folke/tokyonight.nvim
background       = 0xff1a1b26
base             = 0xff16161e
alternate_base   = 0xff292e42
text             = 0xffc0caf5
bright_text      = 0xffc0caf5
link_text        = 0xff7aa2f7   # blue
accent           = 0xffbb9af7   # magenta
accent_secondary = 0xff7dcfff   # cyan
